[project]
authors = ["Janina Wibker <me@janina.lol>"]
channels = ["conda-forge"]
name = "numerik2"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python="3.12.*"
pip="*"
numpy=">=2.2.4"
flake8="*"
ruff="*"
more-itertools="*"
marimo = ">=0.13.6,<0.14"

